name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest 

      - name: Install Dependencies
        run: sudo apt-get install libboost-all-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -GNinja ./..
          ninja
          
      - name: Smoke Test
        run: |
          cd build
          ./stc
